### ISSUE TITLE
Demo Setup

### ISSUE THREAD

**Issue by Teodelas** [Microsoft/SmartHotel360-Website#20] opened 2018-09-21 15:54 UTC
I'm a MSFT FTE.  I need to set this up on VMs to show migration and refactoring.  Please include instructions on deploying this to VMs.  Also, the instructions don't cover how to create the SQL DB (with relevant data).

**Comment by dsanchezcr** [comment] 2018-10-18 21:15
We will have an environment (VM) available internally, it is in the roadmap. Feel free to join to the Teams that we have for SmartHotel360. I'm closing this issue since it's a feature request and not a bug.

**Closed as completed by dsanchezcr** 2018-10-18 21:15 UTC
